test:
  stripe_secret_key: "sk_test_OGO6Th4XlLrPTcNjOSyVOfqx"
  stripe_publishable_key: "pk_test_kNmTDcRkjtxdIdE4fYhjavNw"
development:
  stripe_secret_key: "sk_test_OGO6Th4XlLrPTcNjOSyVOfqx"
  stripe_publishable_key: "pk_test_kNmTDcRkjtxdIdE4fYhjavNw"