development:
  adapter: postgresql
  encoding: unicode
  database: myflix-dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: myflix-test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: myflix-prod
  pool: 5